DataDog/security-agent-policies

runtime/default.policy

In this PR, I have updated the default policies for the security agent.
Rules removed:
- Hidden File: The hidden file detection has been deemed too noisy. This may be readded at a later date after further research.
Rules added:
- Nsswitch.conf Modification: nsswitch.conf modification from an unusual source process can be an indicator of an exploit attempting to interfere with authentication
- PAM Modification: PAM modification from an unusual source process can be an indicator of an exploit attempting to interfere with authentication
- Cron scheduling from an Unauthorized Client: If cron scheduling occurs from a process other than "at" or "crontab", it could indicate a persistence attempt by an attacker.
- Unauthorized Kernel Modification: Accessing files in /boot/ could indicate an …

v1.0.1 of default policy. Removed 1 rule, added 8

---

runtime/default.policy

Fix a few rules of the default policy:
- permissions_changed: fixed one watched folder from "/usr/bin/local/*" to "/usr/local/bin/*"
- kernel_module: watch both /lib/modules/* /usr/lib/modules/*
- systemd_modification: watch "/usr/lib/systemd/system/*" instead of "/lib/systemd/system/*"
The last 2 changes are required because /lib is now a symlink to /usr/lib. The runtime security agent resolve paths to the symlink target.

Runtime default policy fixes

---

runtime/default.policy

- Tune out common noise created by system processes (sudo and cron) for credential_accessed and authentication_logs_accessed
- Tune out common noise created by Postgres database for PCI 11.5 FIM rule
- Make sure the PCI 11.5 rule captures file creates as well as writes
Generate higher fidelity events based on usage patterns across installed systems

Tune Default FIM Rules

---

runtime/default.policy

This PR removes the MITRE techniques tags from the default runtime security policy rules.
MITRE tags are added by the backend rules and do not need to be added by the agent.
This PR is related to https://github.com/DataDog/datadog-agent/pull/6542 which re-enables tags forwarding from the agent.

Remove MITRE tags

---

runtime/default.policy

The newest update of the security agent policy! This update includes:
- Macros! Macros are available in the security-agent policy language. The are reusable components of the same language used to express rules. Use them to create allow-lists, re-use partial expressions, and more!
- Better signal:noise ratio for existing rules: We've identified standard system activity across our rule-set, and have introduced allow-lists of processes to tune out that activity. Defined as macros, we have lists for standard container processes, system credential processes, and of course, common Datadog Agent processes.
- Improvements to existing rules: Additionally we've tweaked the existing rules to fine more suspicious activity, and better help you maintain compliance
Continuous improvement!
Anything else …

Default.policy version 1.1.0

---

compliance/containers/cis-kubernetes-1.5.1.yaml

Updates cis-kubernetes-1.5.1-4.2.4
- Removes role restriction to run the check on all K8s nodes.
- Fails the test if read-only-port is not present. When read-only-port is not present, it [defaults to 10255](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/#:~:text=--read-only-port).
- Check for setting in the config file.  Currently hardcoded to `/var/lib/kubelet/config.yaml`.
Given false checks.

Update to cis-kubernetes-1.5.1-4.2.4

---

compliance/containers/cis-kubernetes-1.5.1.yaml

Updates a Critical rule where the absence of the flag is a valid configuration.

Update to rule cis-kubernetes-1.5.1-1.2.4

---

runtime/default.policy

- Import generated rules from the security monitoring repository
- Provide more coverage - all event types - for file monitoring rules
- Remove logs_removed, logs_altered and permissions_changed rules
Many rules only handled the 'open' event type which may some accesses (such as the
'vi' use case) to not be catched by the default rules.

Handle all event types for file monitoring rules

---

compliance/containers/cis-docker-1.2.0.yaml

Removes `\n` from rule condition. 
I came across this while modifying the rule in `security-monitoring` repo. I actually don't know if the grammar supports having `\n` inside the condition. If it does please ignore my PR. 

Remove \n from rule condition

---

.github/workflows/runtime.yaml

This PR splits the check policies Github Action into two so that it's clearer on which version of the agent the check is failing.
The `if: ${{ always() }}` is used so that the second step is always run, even if the first failed.
Currently the two checks are done in the same step so when one is failing it fails the whole step and you need to look at the logs to figure out what is happening. With this PR the check if first done on the current development version of the agent then on the last release, in two separate steps.

Split check policies actions to increase clarity

---

compliance/containers/cis-kubernetes-1.5.1.yaml

It seems resourceType field was missing for 2 rules cis-kubernetes-1.5.1-1.3.2 and cis-kubernetes-1.5.1-1.3.3, leading to an incorrect resource type name (kubernetes_node) being used. So I added the missing fields
Issue spotted with the resource name

fix resource type kubernetes

---

.github/CODEOWNERS

Remove container integrations from the codeowners
container integrations doesn't own compliance monitoring anymore

Remove container integrations from the CODEOWNERS file

---

runtime/default.policy

This PR introduces the CWS agent side rule to detect the Dirty Pipe vulnerability.
Add a detection for a newly disclosed CVE

[CWS] Dirty Pipe detection

---

compliance/containers/cis-kubernetes-1.5.1.yaml

This reverts commit 335cab44fc3775c343ea4ebbbb32c160c4d77c18.
This PR reintroduces the host selectors

Revert removal of host selectors

---

.github/workflows/release.yaml
.github/workflows/runtime.yaml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

remove usage of set-output (deprecated)

---

runtime/default.policy

Remove the CWS agent rule `net_util_exfiltration` until it can be improved.

Policy v1.8.2 - remove net_util_exfiltration

---

compliance/containers/cis-kubernetes-1.5.1.yaml

`hostSelector` field is not used anymore and can be removed from infrastructure configurations.
Associated to this changes on agent side: https://github.com/DataDog/datadog-agent/pull/14770.

[CSPM] remove hostSelector field CSPM infrastructure rules

---

compliance/containers/cis-kubernetes-1.5.1.yaml

Previous PR #95 did not prune all existing fields from cis-kubernetes-1.5.1
`hostSelector` field is not used anymore and can be removed from infrastructure configurations.
Associated to this changes on agent side: https://github.com/DataDog/datadog-agent/pull/14770.

[CSPM] remove some missing hostSelector field in cis-kubernetes-1.5.1

---

runtime/default.policy

Sync with internal repo. Improving the `net_util_exfiltration` rule.

[CWS] Update policy to v1.9.1

---

compliance/containers/cis-rhel7-3.1.1.yaml
compliance/containers/cis-rhel8-2.0.0.yaml

This change fixes RHEL 7 and 8 CIS Benchmark versions.
Here are the versions of the Linux CIS Benchmarks we use:
```
cis-rhel7      Red Hat Linux 7 Benchmark   v3.1.1 2021-05-21
cis-rhel8      Red Hat Linux 8 Benchmark   v2.0.0 2022-02-23
cis-rhel9      Red Hat Linux 9 Benchmark   v1.0.0 2022-11-28
cis-ubuntu2004 Ubuntu 20.04 LTS Benchmark  v1.0.0 2020-07-21
cis-ubuntu2204 Ubuntu 22.04 LTS Benchmark  v1.0.0 2022-08-30
cis-amzn2      Amazon Linux 2 Benchmark    v1.0.0 2019-04-19
cis-al2023     Amazon Linux 2023 Benchmark v1.0.0 2023-03-07
```

[CSPM] Fix RHEL 7 and 8 CIS Benchmark versions

---

compliance/containers/cis-rhel7-3.1.1.yaml
compliance/containers/cis-rhel8-2.0.0.yaml
compliance/containers/cis-rhel9-1.0.0.yaml
compliance/containers/cis-ubuntu2204-1.0.0.yaml

This change disables the `xccdf_org.ssgproject.content_rule_accounts_user_dot_no_world_writable_programs`
rule, since it could lead to OOM on some systems.

[CSPM] Disable content_rule_accounts_user_dot_no_world_writable_programs rule

---

compliance/containers/cis-rhel7-3.1.1.yaml
compliance/containers/cis-rhel8-2.0.0.yaml
compliance/containers/cis-rhel9-1.0.0.yaml
compliance/containers/cis-ubuntu2004-1.0.0.yaml
compliance/containers/cis-ubuntu2204-1.0.0.yaml

This change disables the `xccdf_org.ssgproject.content_rule_file_permissions_ungroupowned` rule, since it could allocate a large amount of memory on large file systems.

[CSPM] Disable content_rule_file_permissions_ungroupowned rule

---

runtime/default.policy

This PR creates a v1.19.1 policy, backporting the runc_leaky_fd rule on top of the policy shipped with agent 7.51. This policy will be shipped with agent 7.51.1

backport chdir rule to v0.19.1 policy

---

runtime/default.policy

This PR fixes the path and format of the `suspicious_dll_write` to match recent glob changes on windows.

fix `suspicious_dll_write` agent rule

---

runtime/default.policy

This PR fixes the `suspicious_dll_write` in relation to recent device path field renaming

[CWS] fix suspicious dll rule with recent device path renaming

---

runtime/default.policy

Updates the policy to v1.28.1 which includes a change to the runc leaky vessels rule
Increasing rule confidence

Update Leaky Vessels rule

---

runtime/default.policy

Update runtime policy to v1.29.1

---

runtime/default.policy

* Tune some rules
* Remove noisy `interpreter_outbound_connection` rule

[CWS] Sync policy to 1.40.0

---

compliance/containers/cis-docker-1.2.0-5.31.rego

Syncing the last change made to Docker policies made to allow list specific containers for rule 5.31 of Docker benchmarks.

[CSPM] Sync docker policies
