DataDog/security-agent-policies

.github/CODEOWNERS

Updates `CODEOWNERS`.
Simplifies code reviews (I hope).

Refine code owner designation to simplify code reviews

---

compliance/containers/cis-kubernetes-1.5.1.yaml

Following testing on OpenShift and GKE by @ahmed-mez 

Fix some issues with Kubernetes CIS

---

.github/workflows/runtime.yaml

This PR adds a runtime policy check in CI.
The goal is to make sure that new policies are valid.

Check the runtime policies

---

.github/workflows/runtime.yaml
runtime/default.policy

Use the new taxonomy in default runtime policy

Use new taxonomy in runtime default policy

---

.github/workflows/runtime.yaml
runtime/default.policy

Reverts DataDog/security-agent-policies#17

Revert "Use new taxonomy in runtime default policy"

---

runtime/default.policy

Policy version 1.2.0 draft PR.

Ayush.kapur/policy 1 2 0

---

.github/workflows/runtime.yaml
runtime/default.policy

Use more specific rules regarding log files
The logs_removed and logs_altered are amongst the noisiest rules

Use more specific logs related rules

---

runtime/default.policy

Reduce noise for most of the rules

Bump policy to 1.3.3

---

compliance/containers/cis-kubernetes-1.5.1.yaml

This PR updates a few rules to better handle setting in the kubelet config file.

Updates to better handle kubelet config file

---

compliance/containers/cis-kubernetes-1.5.1.yaml

Rename kubernetes_worker and kubernetes_master to kubernetes_worker_node and kubernetes_master_node

Add _node suffix to kubernetes_master and kubernetes_worker

---

runtime/default.policy

[runtime-security] use wildcard for python and add /usr/bin/dash

---

runtime/default.policy

Allow package managers for binaries and credentials modifications.
Package managers trigger many actions such as initramfs creation, new users and group

Allow package managers

---

runtime/default.policy

Add selinux rule

---

compliance/containers/cis-kubernetes-1.5.1.yaml

After recent changes to the agent evaluation we should be able to suport it.
Customer reported bug, see https://datadoghq.atlassian.net/browse/CM-508 

[CM-508] Support tls bootstrap in kubernetes policy

---

compliance/containers/cis-docker-1.2.0.yaml
runtime/default.policy

Sync policies with security-monitoring repo

---

compliance/containers/audit-rule-common.rego
compliance/containers/cis-docker-1.2.0-1.2.2.rego
compliance/containers/cis-docker-1.2.0-2.1.rego
compliance/containers/cis-docker-1.2.0-2.2.rego
compliance/containers/cis-docker-1.2.0-3.7.rego
compliance/containers/cis-docker-1.2.0-3.8.rego
compliance/containers/cis-docker-1.2.0-4.6.rego
compliance/containers/cis-docker-1.2.0-5.2.rego
compliance/containers/cis-docker-1.2.0.yaml
compliance/containers/cis-kubernetes-1.5.1-1.2.14.rego
compliance/containers/cis-kubernetes-1.5.1-1.2.15.rego
compliance/containers/cis-kubernetes-1.5.1-4.2.10.rego
compliance/containers/cis-kubernetes-1.5.1-4.2.11.rego
compliance/containers/cis-kubernetes-1.5.1-4.2.2.rego
compliance/containers/cis-kubernetes-1.5.1-4.2.4.rego
compliance/containers/cis-kubernetes-1.5.1-4.2.5.rego
compliance/containers/cis-kubernetes-1.5.1-4.2.6.rego
compliance/containers/cis-kubernetes-1.5.1-4.2.7.rego
compliance/containers/cis-kubernetes-1.5.1-5.1.5.rego
compliance/containers/cis-kubernetes-1.5.1.yaml
compliance/containers/container-generic-rule.rego
compliance/containers/file-matches-regexp.rego
compliance/containers/file-owner-rule-common.rego
compliance/containers/file-permissions-common.rego
compliance/containers/helpers.rego
compliance/containers/process-common-rule.rego

This PR syncs CSPM benchmarks with internal repository.

Sync security agent policies with internal repo - 11/29/2021

---

compliance/containers/process-common-rule.rego

Sync security agent policies with internal repo - 12/09/2021
Bug fix

Sync security agent policies with internal repo - 12/09/2021

---

runtime/default.policy

Sync with internal repo - fix globs

---

runtime/default.policy

Add pwnkit detection rule

---

.github/workflows/runtime.yaml

Fix CI by adding configuration files

---

compliance/containers/cis-kubernetes-1.5.1-4.2.5.rego

Sync with internal repo - fix time units parsing

---

runtime/default.policy

Sync with internal repo - improve net utils rule

---

runtime/default.policy

Sync with internal repo

---

runtime/default.policy

adds tomcat to webapp macro
to detect exploitation of spring4shell

syncing the addition of tomcat to webapp macro

---

compliance/containers/cis-kubernetes-1.5.1.yaml

This PR removes `hostSelector` from cis-kubernetes benchmark

Sync with internal repository

---

runtime/default.policy

reduce complexity of some rules and re-add containerd/dockerd filters

---

runtime/default.policy

Sync with internal repository - fix `new_binary_execution_in_container`

---

runtime/default.policy

Sync with internal repository - DNS rules

---

.github/workflows/release.yaml
.github/workflows/runtime.yaml

Upgrade github actions jobs

---

compliance/containers/cis-docker-1.2.0-1.2.2.rego
compliance/containers/cis-docker-1.2.0-3.7.rego
compliance/containers/cis-docker-1.2.0-3.8.rego
compliance/containers/cis-docker-1.2.0-5.7.rego
compliance/containers/cis-kubernetes-1.5.1-5.3.2.rego
compliance/containers/docker-info-rule-common.rego
compliance/containers/psp-rule-common.rego

Revert rego changes requiring opa > 0.37.2

---

compliance/containers/cis-kubernetes-1.5.1.yaml

Reinstate host-selectors

---

.github/workflows/runtime.yaml
testdata/cws/7.27.0.expected
testdata/cws/7.28.1.expected
testdata/cws/7.29.1.expected
testdata/cws/7.30.1.expected
testdata/cws/7.31.1.expected
testdata/cws/7.32.4.expected
testdata/cws/7.33.1.expected
testdata/cws/7.34.0.expected
testdata/cws/7.35.2.expected

Add tests against every agent version

---

compliance/containers/cis-docker-1.2.0.yaml
compliance/containers/cis-kubernetes-1.5.1.yaml

Sync with internal repo - CSPM only

---

runtime/default.policy
testdata/cws/7.27.0.expected

This PR sync the CWS policies with internal repo. It contains bugfixes and improvements from release [1.7.2](https://github.com/DataDog/security-monitoring/releases/tag/v1.7.2).

Sync with internal repo release 1.7.2

---

compliance/containers/cis-docker-1.2.0-2.2.rego
compliance/containers/cis-docker-1.2.0-2.3.rego
compliance/containers/cis-docker-1.2.0-2.6.rego
compliance/containers/cis-kubernetes-1.5.1-4.2.10.rego
compliance/containers/cis-kubernetes-1.5.1-4.2.11.rego
compliance/containers/cis-kubernetes-1.5.1-4.2.4.rego
compliance/containers/cis-kubernetes-1.5.1-4.2.5.rego
compliance/containers/cis-kubernetes-1.5.1-4.2.6.rego
compliance/containers/cis-kubernetes-1.5.1-4.2.7.rego
compliance/containers/process-common-rule.rego

Update the rules to handle processes as arrays

---

runtime/default.policy

[CWS] Update policy to v1.9.0

---

runtime/default.policy

Update policy with new agent rules and tunes

[CWS] Update policy to v1.10.0

---

compliance/containers/cis-docker-1.2.0.yaml
runtime/default.policy

[CWS] sync threat score tags

---

runtime/default.policy

[CWS] Update policy to v1.11.2

---

compliance/containers/cis-rhel7-1.0.0.yaml
compliance/containers/cis-rhel8-1.0.0.yaml
compliance/containers/cis-rhel9-1.0.0.yaml
compliance/containers/cis-ubuntu2004-1.0.0.yaml
compliance/containers/cis-ubuntu2204-1.0.0.yaml

This change removes the service rules on Ubuntu and Red Hat.
The service rules are broken with the version of
security policy content we use.
On RHEL, OpenSCAP always return true when evaluating the runlevel tests:
I: oscap:   Evaluating runlevel test 'oval:ssg-test_runlevel5_crond_on:tst:1': Runlevel test.
I: oscap:     Querying runlevel object 'oval:ssg-obj_runlevel5_crond_on:obj:1', flags: 0.
I: oscap:     Creating new syschar for runlevel_object 'oval:ssg-obj_runlevel5_crond_on:obj:1'.
I: oscap:     I will run runlevel_probe_main:
I: oscap:     Test 'oval:ssg-test_runlevel5_crond_on:tst:1' requires that zero or more objects defined by 'oval:ssg-obj_runlevel5_crond_on:obj:1' exist on the system.
I: oscap:     0 objects defined by 'oval:ssg-obj_runlevel5_crond_on:obj:1' exist on the …

[CSPM] Remove service rules on Ubuntu and Red Hat

---

compliance/containers/cis-rhel7-1.0.0.yaml
compliance/containers/cis-rhel8-1.0.0.yaml
compliance/containers/cis-rhel9-1.0.0.yaml
compliance/containers/cis-ubuntu2004-1.0.0.yaml
compliance/containers/cis-ubuntu2204-1.0.0.yaml

This change sorts compliance rules by rule IDs.

[CSPM] Sync with internal repository

---

runtime/default.policy

Updates latest agent policy to v1.14.0

uploaded latest agent policy

---

runtime/default.policy

[CWS] Update policy to v1.15.0

---

runtime/default.policy

[CWS] Update policy to v1.6.1

---

runtime/default.policy

Updating agent policy for agent release
New agent release 

updated default policy

---

runtime/default.policy

Adding windows rules 
Removing deleted rules
setting old rules to deleted

updated policy to 1.18.4

---

runtime/default.policy

Contains policy bug fixes found during windows beta agent QA

Policy v1.18.4

---

runtime/default.policy

Update runtime policy to v1.19.0. Several rule updates and new rules.

[CSM-T] Update policy to v1.19.0

---

runtime/default.policy

Enable auto suppression for `net_util_in_container_v2`

Add suppression for net_util_in_container_v2

---

runtime/default.policy

Update policy for next release

[CSM-T] Update policy to v1.22.0

---

runtime/default.policy

update policy to v 1.23.0

---

runtime/default.policy

Small updates to Linux runtime security rules

Update runtime security policy to 1.24.0

---

runtime/default.policy

Updating policy to v1.25.1
To fix registry expressions

updated policy to v1.25.1

---

runtime/default.policy

Adds several Windows rules and updates other rules.

[CSM-T] Update policy to 1.26.0

---

runtime/default.policy

updating to latest policy

---

runtime/default.policy

updated policy to v1.28.2

---

runtime/default.policy

Small update to the pip potential path

update policy to v1.28.3

---

runtime/default.policy

Adding release v1.29.0 to agent

created release v1.29.0

---

compliance/containers/stig-ubuntu2004-V1R9.yaml
compliance/containers/stig-ubuntu2204-1.0.0.yaml

Add Ubuntu 20.04 & 22.04 STIG checks to the agent.

add stig rules to agent

---

runtime/default.policy

Publish new rules and rule updates for next Agent release.

[CWS] Update policy to v1.30.0

---

runtime/default.policy

[CWS] Update runtime policy to v1.31.1

---

runtime/default.policy

updated policy to v1.32.0

---

runtime/default.policy

* Update policy with new process, file, and network rules
* Also includes the hash action on several existing rules

Update policy to 1.35.0

---

runtime/default.policy

Bump policy to v1.36.0 which includes several net new rules and simplified regex.

[CWS] New rules and cleaned up regex

---

.github/workflows/release.yaml

give contents: write permissions to release workflow

---

runtime/default.policy

Tuning several rules to reduce signal volume

[CWS] Update policy for release

---

runtime/default.policy

Add MITRE tags to agent events and add missing `container.id` field when container start time is referenced.

Add tags and missing container.id

---

runtime/default.policy

[CWS] Add 1.46.0 policy for release

---

runtime/default.policy

Adds and updates rules from policy 1.50.0

Update runtime policy to 1.50.0
